# flake8: noqa
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 470)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 500, 450))
        self.textEdit.setToolTip("")
        self.textEdit.setStatusTip("")
        self.textEdit.setWhatsThis("")
        self.textEdit.setAccessibleName("")
        self.textEdit.setAccessibleDescription("")
        self.textEdit.setAccessibleIdentifier("")
        self.textEdit.setStyleSheet("")
        self.textEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">qweeqw</p></body></html>")
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuText_view = QtWidgets.QMenu(parent=self.menuEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Edit/main_theme/text-format.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuText_view.setIcon(icon)
        self.menuText_view.setObjectName("menuText_view")
        self.menuWeight = QtWidgets.QMenu(parent=self.menuText_view)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Edit/main_theme/weight.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuWeight.setIcon(icon1)
        self.menuWeight.setObjectName("menuWeight")
        self.menuColor = QtWidgets.QMenu(parent=self.menuEdit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Edit/main_theme/palette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuColor.setIcon(icon2)
        self.menuColor.setObjectName("menuColor")
        self.menuFeatures = QtWidgets.QMenu(parent=self.menubar)
        self.menuFeatures.setObjectName("menuFeatures")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuChange_language = QtWidgets.QMenu(parent=self.menuSettings)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Settings/main_theme/language.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuChange_language.setIcon(icon3)
        self.menuChange_language.setObjectName("menuChange_language")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/File/main_theme/file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionNew.setIcon(icon4)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/File/main_theme/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/File/main_theme/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/File/main_theme/save (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSave_as.setIcon(icon7)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/File/main_theme/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName("actionExit")
        self.actionReset_settings = QtGui.QAction(parent=MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Edit/main_theme/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionReset_settings.setIcon(icon9)
        self.actionReset_settings.setObjectName("actionReset_settings")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Settings/main_theme/information-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFind = QtGui.QAction(parent=MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Features/main_theme/text.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionFind.setIcon(icon11)
        self.actionFind.setObjectName("actionFind")
        self.actionFindReplace = QtGui.QAction(parent=MainWindow)
        self.actionFindReplace.setObjectName("actionFindReplace")
        self.actionBold = QtGui.QAction(parent=MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Menu/main_theme/bold.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionBold.setIcon(icon12)
        font = QtGui.QFont()
        font.setBold(True)
        self.actionBold.setFont(font)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtGui.QAction(parent=MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Menu/main_theme/italic-font.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionItalic.setIcon(icon13)
        font = QtGui.QFont()
        font.setItalic(True)
        self.actionItalic.setFont(font)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtGui.QAction(parent=MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Menu/main_theme/underline.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUnderline.setIcon(icon14)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.actionUnderline.setFont(font)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionCrossOut = QtGui.QAction(parent=MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Menu/main_theme/cross-out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCrossOut.setIcon(icon15)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.actionCrossOut.setFont(font)
        self.actionCrossOut.setObjectName("actionCrossOut")
        self.actionReadOnly = QtGui.QAction(parent=MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Edit/main_theme/view.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionReadOnly.setIcon(icon16)
        self.actionReadOnly.setObjectName("actionReadOnly")
        self.actionThin = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionThin.setFont(font)
        self.actionThin.setObjectName("actionThin")
        self.actionLight = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionLight.setFont(font)
        self.actionLight.setObjectName("actionLight")
        self.actionNormal = QtGui.QAction(parent=MainWindow)
        self.actionNormal.setObjectName("actionNormal")
        self.actionMedium = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionMedium.setFont(font)
        self.actionMedium.setObjectName("actionMedium")
        self.actionDemiBold = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionDemiBold.setFont(font)
        self.actionDemiBold.setObjectName("actionDemiBold")
        self.action1 = QtGui.QAction(parent=MainWindow)
        self.action1.setObjectName("action1")
        self.actionUndo = QtGui.QAction(parent=MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Edit/main_theme/undo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionUndo.setIcon(icon17)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(parent=MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Edit/main_theme/redo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionRedo.setIcon(icon18)
        self.actionRedo.setObjectName("actionRedo")
        self.actionThemes = QtGui.QAction(parent=MainWindow)
        self.actionThemes.setObjectName("actionThemes")
        self.actionRed = QtGui.QAction(parent=MainWindow)
        self.actionRed.setObjectName("actionRed")
        self.actionOrange = QtGui.QAction(parent=MainWindow)
        self.actionOrange.setObjectName("actionOrange")
        self.actionYellow = QtGui.QAction(parent=MainWindow)
        self.actionYellow.setObjectName("actionYellow")
        self.actionGreen = QtGui.QAction(parent=MainWindow)
        self.actionGreen.setObjectName("actionGreen")
        self.actionBlue = QtGui.QAction(parent=MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionPurple = QtGui.QAction(parent=MainWindow)
        self.actionPurple.setObjectName("actionPurple")
        self.actionGray = QtGui.QAction(parent=MainWindow)
        self.actionGray.setObjectName("actionGray")
        self.actionBlack = QtGui.QAction(parent=MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionResetColor = QtGui.QAction(parent=MainWindow)
        self.actionResetColor.setObjectName("actionResetColor")
        self.actionResetFormat = QtGui.QAction(parent=MainWindow)
        self.actionResetFormat.setIcon(icon9)
        self.actionResetFormat.setObjectName("actionResetFormat")
        self.actionBold2 = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        self.actionBold2.setFont(font)
        self.actionBold2.setObjectName("actionBold2")
        self.actionExtraBold = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionExtraBold.setFont(font)
        self.actionExtraBold.setObjectName("actionExtraBold")
        self.actionResetStyle = QtGui.QAction(parent=MainWindow)
        self.actionResetStyle.setIcon(icon9)
        self.actionResetStyle.setObjectName("actionResetStyle")
        self.actionMenu = QtGui.QAction(parent=MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Settings/main_theme/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionMenu.setIcon(icon19)
        self.actionMenu.setObjectName("actionMenu")
        self.actionWhite = QtGui.QAction(parent=MainWindow)
        self.actionWhite.setObjectName("actionWhite")
        self.actionFind_and_replace_text = QtGui.QAction(parent=MainWindow)
        self.actionFind_and_replace_text.setObjectName("actionFind_and_replace_text")
        self.actionRussian = QtGui.QAction(parent=MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Menu/png/russia.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionRussian.setIcon(icon20)
        self.actionRussian.setObjectName("actionRussian")
        self.actionEnglish = QtGui.QAction(parent=MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Menu/png/united-kingdom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionEnglish.setIcon(icon21)
        self.actionEnglish.setObjectName("actionEnglish")

        self.actionGoto = QtGui.QAction(parent=MainWindow)
        self.actionGoto.setObjectName("actionGoto")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Features/main_theme/goto.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionGoto.setIcon(icon26)

        self.actionCaps = QtGui.QAction(parent=MainWindow)
        self.actionCaps.setObjectName("actionCaps")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Features/main_theme/caps.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCaps.setIcon(icon27)

        self.actionLower = QtGui.QAction(parent=MainWindow)
        self.actionLower.setObjectName("actionCaps")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Features/main_theme/uncaps.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLower.setIcon(icon28)

        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuWeight.addAction(self.actionThin)
        self.menuWeight.addAction(self.actionLight)
        self.menuWeight.addAction(self.actionNormal)
        self.menuWeight.addAction(self.actionMedium)
        self.menuWeight.addAction(self.actionDemiBold)
        self.menuWeight.addAction(self.actionBold2)
        self.menuWeight.addAction(self.actionExtraBold)
        self.menuText_view.addAction(self.actionBold)
        self.menuText_view.addAction(self.actionItalic)
        self.menuText_view.addAction(self.actionUnderline)
        self.menuText_view.addAction(self.actionCrossOut)
        self.menuText_view.addAction(self.menuWeight.menuAction())
        self.menuText_view.addSeparator()
        self.menuText_view.addAction(self.actionResetFormat)
        self.menuColor.addAction(self.actionRed)
        self.menuColor.addAction(self.actionOrange)
        self.menuColor.addAction(self.actionYellow)
        self.menuColor.addAction(self.actionGreen)
        self.menuColor.addAction(self.actionBlue)
        self.menuColor.addAction(self.actionPurple)
        self.menuColor.addAction(self.actionGray)
        self.menuColor.addAction(self.actionWhite)
        self.menuColor.addAction(self.actionBlack)
        self.menuColor.addSeparator()
        self.menuColor.addAction(self.actionResetColor)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuColor.menuAction())
        self.menuEdit.addAction(self.actionReadOnly)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuText_view.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionResetStyle)
        self.menuFeatures.addAction(self.actionFind)
        self.menuFeatures.addAction(self.actionGoto)
        self.menuFeatures.addSeparator()
        self.menuFeatures.addAction(self.actionCaps)
        self.menuFeatures.addAction(self.actionLower)
        self.menuChange_language.addAction(self.actionRussian)
        self.menuChange_language.addAction(self.actionEnglish)
        self.menuSettings.addAction(self.actionMenu)
        self.menuSettings.addAction(self.menuChange_language.menuAction())
        self.menuSettings.addAction(self.actionReset_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFeatures.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Menu/main_theme/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionDelete.setIcon(icon22)
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Menu/main_theme/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCopy.setIcon(icon23)
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Menu/main_theme/paste.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPaste.setIcon(icon24)
        self.actionCut = QtGui.QAction(parent=MainWindow)
        self.actionCut.setObjectName("actionCut")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Menu/main_theme/cut.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCut.setIcon(icon25)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notepad"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuText_view.setTitle(_translate("MainWindow", "Text view"))
        self.menuWeight.setTitle(_translate("MainWindow", "Weight"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionGoto.setText(_translate("MainWindow", "Go to"))
        self.actionGoto.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionCaps.setText(_translate("MainWindow", "Caps"))
        self.actionLower.setText(_translate("MainWindow", "Lower"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.menuColor.setTitle(_translate("MainWindow", "Color"))
        self.menuFeatures.setTitle(_translate("MainWindow", "Features"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuChange_language.setTitle(_translate("MainWindow", "Change language"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionReset_settings.setText(_translate("MainWindow", "Reset settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFind.setText(_translate("MainWindow", "Find text"))
        self.actionFindReplace.setText(_translate("MainWindow", "Find and replace text"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionCrossOut.setText(_translate("MainWindow", "Cross out"))
        self.actionReadOnly.setText(_translate("MainWindow", "Read-only"))
        self.actionThin.setText(_translate("MainWindow", "Thin"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionNormal.setText(_translate("MainWindow", "Normal (Regular)"))
        self.actionMedium.setText(_translate("MainWindow", "Medium"))
        self.actionDemiBold.setText(_translate("MainWindow", "DemiBold"))
        self.action1.setText(_translate("MainWindow", "1 - Active"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionThemes.setText(_translate("MainWindow", "Themes"))
        self.actionRed.setText(_translate("MainWindow", "Red"))
        self.actionOrange.setText(_translate("MainWindow", "Orange"))
        self.actionYellow.setText(_translate("MainWindow", "Yellow"))
        self.actionGreen.setText(_translate("MainWindow", "Green"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionPurple.setText(_translate("MainWindow", "Purple"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionResetColor.setText(_translate("MainWindow", "Reset color"))
        self.actionResetFormat.setText(_translate("MainWindow", "Reset format"))
        self.actionBold2.setText(_translate("MainWindow", "Bold"))
        self.actionExtraBold.setText(_translate("MainWindow", "ExtraBold"))
        self.actionResetStyle.setText(_translate("MainWindow", "Reset style"))
        self.actionMenu.setText(_translate("MainWindow", "Menu"))
        self.actionWhite.setText(_translate("MainWindow", "White"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionRussian.setText(_translate("MainWindow", "Russian"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
